In [1]:
import numpy as np
import pypianoroll as pr
import pickle
from tqdm import tqdm

In [2]:
import os
os.chdir('..')

In [3]:
pwd

'/mnt/md1/user_victor/automatic_melody_harmonization'

In [6]:
f = open('./data/tempos', 'rb')
tempos = pickle.load(f)

In [15]:
f = open('./data/downbeats', 'rb')
downbeats = pickle.load(f)

In [16]:
downbeats[0]

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [13]:
tempos[2].shape

(792,)

In [9]:
len(tempos)

17430

In [5]:
for i in tqdm(range(1)):
    melody = np.load('./melody_baseline.npy')
    chord = np.load('./number_96.npy')
    chord_onehot = np.load('./onehot_96.npy')
    length = np.load('./length.npy')
    weight_chord = np.load('./weight_chord.npy')

    melody_data = np.load('./melody_data.npy')
    chord_groundtruth = np.load('./chord_groundtruth.npy')

    f = open('./tempos', 'rb')
    tempos = pickle.load(f)
    f.close()
    f = open('./downbeats', 'rb')
    downbeats = pickle.load(f)
    f.close()

100%|██████████| 1/1 [06:28<00:00, 388.57s/it]


In [6]:
print('Data from npz:')
print('melody_data shape',melody_data.shape)
print('chord_groundtruth shape',chord_groundtruth.shape)   # 272 為每 2 beats 取出來的 chord
print('length shape',length.shape)
print('tempos shape',len(tempos))
print('downbeats shape',len(downbeats))
print()
print('Data to one hot:')
print('melody shape',melody.shape) 
print('chord_onehot shape',chord_onehot.shape)
print('weight_chord shape',weight_chord.shape)
print('Data to midi number:')
print('chord shape',chord.shape)


Data from npz:
melody_data shape (17430, 13056, 128)
chord_groundtruth shape (17430, 272, 128)
length shape (17430,)
tempos shape 17430
downbeats shape 17430

Data to one hot:
melody shape (17430, 272, 576)
chord_onehot shape (17430, 272, 96)
weight_chord shape (96,)
Data to midi number:
chord shape (17430, 272, 1)


In [12]:
melody[0].shape

(272, 576)

In [11]:
melody_data[0].shape

(13056, 128)

In [7]:
path = '../lead-sheet-dataset/datasets/pianoroll/x/x-ambassadors/unsteady/intro.npz'
# data = np.load(path)
data = pr.Multitrack(path)

In [38]:
print('name:',data.name)
print('resolution:',data.BEAT_RESOLUTION)
print('downbeat shape:',data.downbeat.shape)
print('tempo:',data.tempo[0])
print('melody shape:',data.tracks[0].pianoroll.shape)
print('chord shape:',data.tracks[1].pianoroll.shape)

name: unknown
resolution: 24
downbeat shape: (408,)
tempo: 58.00009860016762
melody shape: (408, 128)
chord shape: (408, 128)


In [1]:
a = None

In [7]:
a is not None

False

In [10]:
np.asarray([0])

array([0])

In [11]:
np.array([0])

array([0])

In [16]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(0, 6))

array([0, 0, 1, 2, 3, 4, 5, 6, 6, 6])

In [17]:
a

[1, 2, 3, 4, 5]